### ISSUE TITLE
bash scripts/translate.sh $model

### ISSUE THREAD

**Issue by ZhenLEI96** [yangbang18/ZeroNLG#1]
RuntimeError: The size of tensor a (192) must match the size of tensor b (576) at non-singleton dimension 0
![image](https://user-images.githubusercontent.com/104677093/233284131-b732a7ad-114e-4f89-9b2a-67f55a21426d.png)
I trained the readme way, but at the time of test, I ran into this problem, what should I do？

**Comment by yangbang18** [comment]
What is the version of your `transformers`? Maybe you can try running with `transformers==4.12.5` or `transformers==4.27.1`, one of which should be ok. I will check how to make the code compatible with different versions of `transformers`.

**Comment by ZhenLEI96** [comment]
Thank you very much for your reply. 
After I changed the transformers version to 4.12.5, I successfully reproduced the program. The version of transformers I used before was 4.28.1.
