### ISSUE TITLE
the t-SNE visualization of vision and multilingual embeddings

### ISSUE THREAD

**Issue by ydwl-lynn** [yangbang18/ZeroNLG#2]
Can you provide the code of the t-SNE visualization of vision and multilingual embeddings? Thank you very much.

**Comment by yangbang18** [comment]
Hi, sorry for the late response. I have several deadlines in the near future. So it will take some time to open source the visualization code.

**Comment by ydwl-lynn** [comment]
Thank you very much.
















At 2023-06-06 11:03:56, "yangbang18" ***@***.***> wrote:

Hi, sorry for the late response. I have several deadlines in the near future. So it will take some time to open source the visualization code.

**Comment by yangbang18** [comment]
Hi, you can refer to the [notebooks/tsne_visualization.ipynb](https://github.com/yangbang18/ZeroNLG/blob/master/notebooks/tsne_visualization.ipynb) we released recently to see how we conduct t-SNE visualization :)
